### ISSUE TITLE
virtual wire library

### ISSUE THREAD

**Issue by balaji126** [sparkfun/RF_Links#2]
please help me for download virtual wire library for arduino

**Comment by bboyho** [comment]
Hi,

I just noticed your comment in this repository. The Virtual Wire library was archived in this repository to work with the example code. You should be able to manually install the library with the Arduino IDE by placing the "VirtualWire" folder in the correct directory. This should be located under "...Documents > Arduino > libraries". Try checking out these instructions from Arduino on [Installing Additional Arduino Libraries](https://www.arduino.cc/en/Guide/Libraries#toc5) for more information.
